"use client";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AuthContext, TaskContext } from "@/context";
import { useAuth } from "@/hooks/useAuth";
import { Header } from "@/components/core/Header/Header";
import { useTasks } from "@/hooks/useTasks";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const auth = useAuth();
  const tasks = useTasks();
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthContext.Provider value={auth}>
          <TaskContext.Provider value={tasks}>
            <Header />
            {children}
          </TaskContext.Provider>
        </AuthContext.Provider>
      </body>
    </html>
  );
}